<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Cần để dùng IFormFile trong CloudinaryService -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarbageCollection.Common\GarbageCollection.Common.csproj" />
    <ProjectReference Include="..\GarbageCollection.DataAccess\GarbageCollection.DataAccess.csproj" />
  </ItemGroup>

</Project>
